spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xianyu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: account-service






